export default {
  TABLE_RESIZE: 'TABLE_RESIZE',
  CHANGE_TEXT: 'CHANGE_TEXT',
  APPLY_STYLES: 'APPLY_STYLES',
  CHANGE_STYLES: 'CHANGE_STYLES',
  CHANGE_TABLE_TITLE: 'CHANGE_TABLE_TITLE',
  UPDATE_DATE: 'UPDATE_DATE'
};
